InVisionApp/kit-deployer

- README.md
- src/deployer
- src/lib/deployer.js
- src/lib/manifests.js
Now by default will not removed resources that are deployed but do not have local manifests, also will skip entire clusters if no generated files are found. This is a change in behavior then previous version which would sync clusters (including deleting deployed resources if not found locally).  This is still available by setting the DELETE_RESOURCES env.
> now by default will not removed resources

- src/lib/manifests.js
- src/lib/status.js
- src/lib/webhook.js
- src/util/timeout-error.js
- test/functional/functional.spec.js
- test/unit/util/timeout-error.spec.js
Adds a custom `TimeoutError` type, which fires when the timing out waiting for the manifests. This status is passed on in the body of the webhook payload as `reason: timeout/other`.
* `npm run test-unit`
* `./test-functional`
> feat: distinguish timeout errors from all other errors and pass this in the webhook payload.

- README.md
- package.json
- src/lib/backup.js
- src/lib/manifests.js
Adds the ability to save the generated manifest to an S3 bucket for backup. This will allow a quick rebuild of any cluster/namespaces. Note only changed manifests are backed up. For a full backup a complete set of generated manifests should be seeded initially.
This can be enabled via an ENV and is **_off_** by default.
Note: The S3 bucket has versioning turned on.
> Adds the ability to save generated manifests to S3 bucket. 

- src/lib/manifests.js
- There is no need to query the resources from a cluster if we do not have any manifests to process for that cluster
- I also handled some lint errors shown in my editor for the `manifest.js` file (basically functions that should have explicitly had a return)
> Only query clusters if we have manifests to process

- .editorconfig
- src/lib/namespaces.js
- We first query clusters for namespaces so that we can create those namespaces if they don't exist yet
- This fixes it so that if there are no namespace files defined, then it won't bother querying clusters for the list of namespaces they currently have
- I also added an `.editorconfig` file by popular demand
> Only query namespaces if needed

- src/lib/manifests.js
- Was not correctly passing `healthCheckGracePeriod` down to the Healthcheck instance which means it always just defaulted to the 10 second grace period
> fix: need to pass graceperiod time to healthcheck instanec

- src/lib/health-check.js
- We noticed false positives because services could generate "unhealthy" reason events when being terminated
- We also noticed services can often have "unhealthy" reason events when first being deployed but the rollout doesn't finish quick enough (too long grace period required). For this reason it's just easier to ignore "unhealthy" reason events completely and only worry about other types of events that are more guaranteed to be a problem (such as CrashLoopBackOff). It may slow down the error detection but it will cause far fewer false positives which is more important
- Also added in a check for objects being killed and events for these objects will be ignored because these are the objects purposefully being shutdown during a deployment and we don't much care for bad events on these …
> False positive healthcheck

- src/lib/health-check.js
- src/lib/kubectl.js
- src/lib/status.js
- test/functional/clusters/configs/badimage-kubeconfig.yaml
- test/functional/clusters/manifests/badimage-cluster/badimage-deployment.yaml
- test/functional/clusters/namespaces/badimage-cluster/badimage-namespace.yaml
- test/functional/functional.spec.js
- The threshold checking wasn't working because our event watcher never emitted events of the same name
- Fixed this by emitting events of the same name only if the count had increased
- I improved on the logging messaging as well
- I added a functional test to verify health check detection
- Run `./test-functional` (has to be used with Docker Machine)
> fix: healthcheck threshold was not working correctly

- src/util/event-error.js
- test/functional/functional.spec.js
- test/unit/util/event-error.spec.js
- We're not really printing the error message multiple times, but rather it's an event error for different involved objects (pods).
- This should fix the perceived error reported in #52
> feat: include the involved object in the event error thrown

- README.md
- src/lib/deployer.js
- src/lib/progress.js
- src/lib/webhook.js
- test/functional/functional.spec.js
- test/unit/lib/progress.spec.js
- Will now emit a `progress` event whenever a cluster has finished being deployed to (or has failed being deployed to)
- It will include a `progress` property in the webhook it sends which will include current deploy progress, the list of clusters remaining, successful, failed, etc
- If needed later this can be expanded on to provide more granular progress information such as pods remaining
- I verified locally using `./test-functional`
- Unit tests were added for the progress class
> Added progress event

- src/lib/deployer.js
- src/lib/progress.js
- was incorrectly emitting progress immediately after manifests were sent to the cluster and was not correctly awaiting the health check of the deployed manifests
- added rounding of the percent to avoid really long nummbbeerrrs
> Fix progress

- src/lib/elroy.js
- forgot to convert the payload to a string before logging it
> fix: stringify elroy payload for log

- src/lib/annotator.js
- src/lib/manifests.js
- test/unit/lib/annotator.spec.js
- Manifests were not generated in time for when we called elroy and thus they were not sent
- This fixes it so that all the required annotations/renaming of manifests are done upfront
- We added Annotator which helps consolidate the annotation/renaming logic for manifests into a single class
> fix: sending generated manifests to elroy

- src/lib/elroy.js
- src/lib/manifests.js
- test/unit/lib/elroy.spec.js
- should not have converted to const as the `remaining` can actually get re-assigned in the current context. Did not want to refactor this out so left it as var
- includes elroy fix so that we don't send requests to elroy if there are no manifests being deployed
> Elroy debug

- src/lib/elroy.js
- test/unit/lib/elroy.spec.js
- elroy expects the manifests to be in `yaml` format
> fix: send to elroy as yaml

- src/util/manifest-diff.js
- test/unit/util/manifest-diff.spec.js
- when we refactored the annotations we forgot that we have to exclude these dynamically generated properties from the manifest diff or else we'll always have false diffs when deploying
> fix: diffs were diffing on dynamicly added properties

- src/util/manifest-diff.js
- test/unit/util/manifest-diff.spec.js
- the diff still wasn't quite right
- we need to diff against the original manifest name
- and we need to drop all annotations if the only annotations that exists were the ones we dynamically created
1. Verified with unit test
> fix: diffs for empty annotations and manifest names

- src/lib/annotator.js
- src/lib/manifests.js
- test/unit/lib/annotator.spec.js
- adds UUID as a deployment annotation
- sorry but we had to go with an inconsistent naming convention for this annotation
> Added UUID as annotation

- src/lib/kubectl.js
- test/unit/lib/kubectl.spec.js
Forgot to extend EventEmitter to allow for emitting events.
Added a simple unit test so I could verify `spawn` events are working and that I didn't break the `spawn` method. (sorry!)
> Fix: kubectl throwing emit error

- src/lib/annotator/annotator.js
- test/unit/lib/annotator.spec.js
We need to allow a base default strategy to be assigned to keep from initial deployments conflicting. Fixes #https://github.com/InVisionApp/engineering-velocity/issues/201 
along with 
https://github.com/InVisionApp/kubernetes-coreos/pull/2028
This PR should be merged before the coreos repo PR.
> allow a default strategy for the selector label

- src/lib/elroy.js
https://github.com/InVisionApp/kit-server/issues/181 
As fas as I can see in loggly https://invisionmain.loggly.com/search#terms=%20json.kubernetes.container_name%3Akitserver-con%20test-rosie-v7&from=2017-08-28T10%3A30%3A12.324Z&until=2017-08-30T10%3A30%3A12.324Z&source_group= 
The problem is when we updating to elroy and there is an error, we emit a log debug with the entire body that contains the manifests. Let me know if  i missing something
> removing debug log with manifests

- package.json
- src/lib/annotator/annotator.js
- src/lib/kubectl.js
- src/lib/strategy/strategies/fast-rollback.js
- test/functional/fast-rollback.spec.js
- test/unit/lib/annotator.spec.js
- test/unit/lib/strategy/strategies/fast-rollback.spec.js
This resolves the Elroy watcher issue for rollbacks via manifests by overwriting the uuid annotation when the manifest is raw.  Elroy uses this annotation so that it knows when the spec has been updated.
relates to #296
> 296 - Overwrite the UUID annotation when using a raw deployment

- README.md
- in-repo.yaml
This was not a real token, however we shouldn't have it in the readme regardless to avoid fears that it could have been a real token.
Verified by following directions [here](https://developer.github.com/v3/#authentication) and doing:
```
curl -H "Authorization: token ccd50691c75bc7bae0a5490ea08ff9dcc9c264a5" https://api.github.com
{
"message": "Bad credentials",
"documentation_url": "https://developer.github.com/v3"
}
```
> Remove fake token used in readme example
